### ISSUE TITLE
Slave-only PCB with ESP8266 and HiLink PM03 PSU

### ISSUE THREAD

**Issue by renne** [jpraus/arduino-opentherm#1]
I suggest a slave-only PCB with an 2,- EUR [Ai-Thinker ESP8266-12F WiFi-module](https://en.wikipedia.org/wiki/ESP8266#Ai-Thinker_modules) and a 2,- EUR [HiLink PM03](http://www.hlktech.net/product_detail.php?ProId=59) power supply unit.

I linked your project to a [Tasmota firmware Opentherm issue](https://github.com/arendst/Sonoff-Tasmota/issues/2295).

**Comment by jpraus** [comment]
Can you elaborate on application for which it would be useful?

Thank you for linking my library.

**Comment by renne** [comment]
An OpenTherm-to-WLAN gateway allows to control the boiler unit via a smartphone app or a central control unit (FHEM, OpenHAB, Domoticz, Node-Red, ...) and can be just installed besides the boiler without wiring hassle.

I suggest to connect the slave interface to GPIO4 and GPIO5 with series resistors for 3.3V/10mA max.. This allows to either use the GPIOs directly with the OpenTherm library running on the ESP8266-12F or as remote serial connection via WLAN with the OpenTherm library running on a central control unit.

Documentation:
[AI-Thinker_ESP-12F](http://www.watterott.com/index.php?page=product&info=4606&dl_media=6570&x0b658=01e1c8a378f68c1052efe406f32a0f8c)
[ESP8266 datasheet](http://espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf)

**Comment by jpraus** [comment]
This project not aims on individual implementations, this is just an interface with all you need to build Arduino based project. So I am not going to put a specific implementations here right now, maybe I will start a separate projects in future.
