### ISSUE TITLE
Schematic V3 

### ISSUE THREAD

**Issue by mrWheel** [jpraus/arduino-opentherm#13]
Hi Jiri,

I'm trying to figure out what and what not to connect to my ESP8266.

I have done the modification (R11 replaces by 4k7 and logic cut and solder).

Connecting 24 volt to the bare shield results in a red led (thats good I think) and 5 volt between GND and the 5Volt header pin, but nothing on the 3v3 header pin (Ok, I was under the impression that the board would provide 3v3 for the ESP .. but it does not!).

As there is no schematic for the Rev3 board.

**Comment by jpraus** [comment]
https://github.com/jpraus/arduino-opentherm/blob/master/doc/shield-schema.png

Yes, the shield does not provide 3V3 voltage since UNO form-factor boards always have a 3V3 voltage regulator. So it would be redundant components that would increase the cost.
