### ISSUE TITLE
Add extra transistor to the rev 3 board

### ISSUE THREAD

**Issue by mrWheel** [jpraus/arduino-opentherm#15]
Jiri,

Can you give me a hint on how to modify the rev 3 board to use the extra transistor (from the rev 4 schematic) on my processor board? (so the transistor(s) are external from the opentherm board).

Also:
Maybe it is good to mention somewhere you need the 3v3 (from the processor board, what ever type) if you want the 3v3 mod to work!

I had to print the gerber files to find out what pins are connected to the processor bord. Maybe you can add that information somewhere in the documentation.

**Comment by jpraus** [comment]
Here you can find the latest schematics:

https://raw.githubusercontent.com/jpraus/arduino-opentherm/master/doc/shield-schematic-doc_rev4.png

The Q6 and R15 are the new components you need. The Base of Q6 is connected to the original Master-IN. Values of R8 and R11 need to be changed as well. It's still experimental. I've just got the new boards yesterday.

Yeah, I will revamp the documentation once I've finish the last revision of the boards to make it up to date.
