### ISSUE TITLE
openterm crashes when reading from SPIFFS or LittleFS

### ISSUE THREAD

**Issue by mrWheel** [jpraus/arduino-opentherm#16]
Has any body have experience with this library in combination with SPIFFS or LittleFS?

As soon as I try to read from the FS the ESP8266 crashes.

I tried it with Arduino ESP8266 core 2.6.3 en 2.7.1

The only thing I can think of is that it has to do with the Timer2 interrupt but at the other hand: why would a memory FS needs a timer interrupt??

Is there a method like OPENTHERM::end() and OPENTHERM::begin() to temporarily stop and start opentherm processing?

**Comment by jpraus** [comment]
Interesting. The library is using Timer2 indeed. Without this library, the littleFS works for you?
Sure you can temporarily stop the processing:

- listen - to start listening on the bus, will auto-stop after a timeout
- stop - stop listening

https://github.com/jpraus/arduino-opentherm/blob/master/src/opentherm.h
