### ISSUE TITLE
24V to 5V Power On led connection 

### ISSUE THREAD

**Issue by niderost** [jpraus/arduino-opentherm#22]
The schematics of the 24V to 5V power supply for the rev4 board (https://raw.githubusercontent.com/jpraus/arduino-opentherm/master/doc/shield-schematic-doc_rev4.png on the README.md page) shows the +5V net connection on the top right. This net seems connected to:
* The 5V pin on the Arduino R3 shield
* The right pin of the JP1 Logic jumper connector
* The +5V terminal of the R14 1k resistor in front of the LED3 Red Power On LED

I am testing my board (which I recently ordered from your Tindie store) with the JP1 LOGIC jumper set to 3.3V but with no external 3.3V power supply / Arduino board connected. I would expect that LED3 would still light up when 24V volt is applied. However, it doesn't. When I switch the JP1 LOGIC jumper to 5.0V, LED3 DOES light up. Might it be the case that the schematic is wrongly indicating that LED3 is powered by the +5V net, and that it is connected to the VLOGIC net instead? If that were the case I would understand why the position of JP1 influences whether LED3 does light up when power is supplied to the 24V terminal of the board.

**Comment by jpraus** [comment]
You are right the LED is connected to Logic Voltage. I've uploaded the latest schematics.
