### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by Weissnix4711** [jpraus/arduino-opentherm#24]
Is there currently any plans to support ESP32?

**Comment by jpraus** [comment]
Hi! Sure, I can do it! You can also try to do it on your own. The only difference gonna be the timers' setup.

**Comment by Weissnix4711** [comment]
I have no idea about arduino timers and interrupts and cpp ain't my strong point, so you better do it lol.

**Comment by vulwater** [comment]
I have just created PR#30 that implements ESP32 support

**Comment by jpraus** [comment]
Thank you

**Comment by bgeer** [comment]
@vulwater I was wondering how you got this library working with an esp32. Could you possibly help me with it?
