### ISSUE TITLE
PCB design files

### ISSUE THREAD

**Issue by soosp** [jpraus/arduino-opentherm#3]
Could you share PCB design files in native or gerber format?

**Comment by jpraus** [comment]
Hi, I've just finished designing Arduino UNO shield, would you be interested?

**Comment by soosp** [comment]
Yes, sure! Will it work with Wemos D1 (not mini)?

**Comment by jpraus** [comment]
Compatible yes, not sure if Wemos D2 and D3 digital pins support interrupt? I will publish these this week. However, they are not tested yet (currently PCBs are on its way from the factory). If it works I will probably sell those.
