### ISSUE TITLE
Why is the value of R5 10k?

### ISSUE THREAD

**Issue by NijzinkM** [jpraus/arduino-opentherm#34]
Thank you for sharing these schematics! I built the gateway myself with Wemos D1 mini and it has been running successfully for a year now, apart from one issue.

About half the time when the gateway restarts, it locks itself. SLAVE IN stays high and MASTER IN stays low permanently. The thermostat doesn't boot. Turning the gateway off and on a few times resolves the issue.

I think it might have something to do with R5. Why does it have a value of 10k and not 1.5k for example? Lowering the value of R5 increases the difference betwoon LOW and HIGH on SLAVE IN. The 10k value might cause the SLAVE IN value to float between HIGH and LOW.

[Simulation of the boiler interface](https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWEAWaAOMaBMA2AnNnmJAdiApOSgMzkCmAtGGAFAAm4eWIeOIWCPr37gAcsjDI07Tt0nJ+g8MgVzxk6QHdFfeTp59ILAE77h1LJWGVq1IwBd+aNOADsfAbvdQQTENWhmMBw7ZCxcakk8BQYYELBXINcsamRXSAQU8DgQNjoAMwBDAFcAG3sWbU9wHEpqvSNTaualMC4fcMb9Fr4LSkpiI1SQAC86ADs6YwZUV3BwaETkakyMLgx4LEY5uth4fYPINAVZ8BYR-iP-S0uXNu5uMcnp2crb2X17qDfLFz79f5GDgJDzIAbeYJ1MQSKRvEE1cFCQxw7zCL7WFGgxHXfqYnHvQF4-56QnaEk3PRYMHfYEqfjUvSQkRgdSwsl0pmMulGdkKRntBpwjkcrB3bl4tGigzfYZPKZMWgQMCLSQrUX3DZwLYMHb8PaHQ7HcCK87+SAKUJmvneR4TeVgagsWV2l7QRULJZqtbqzbbDr6g37I2oE0XWweZL+ageK6254zN1vcP4y2kq346pp0V3byW+E8-HmCneAt53PF5HaYm5zJuZFguZgupKCQRuQsBsoHLMbjLORS1hV2vwhBgOQlt7INFj8gznvfbSjuQzpd1hdRmMuKeb9fb957wVV83p1M3UvRlMXrCRgtN7pKarn3o3O9p18vnLZ74AJRQwmqqz6P0Xb+G6Pj9NACAmH+HjODB-i1gM8AsAA5vBaroTgLi4gADvBX4IDacEQLiaF3no5G1OBLC-oBOAKIIlD0eBIEBLQwEwFBpjIMxaCUHefE+LYt45IJ5EzkYADKKC8ZQgGCcBRSlAAznQHSoeQUrCAgdLWN8ACW4BaboA7clAew4CweHzvCUhriR66CYypkKEYaGEbBLgefiuIAB40DYwxSNwtiNtk2QANYADrKfp4wxWwAD2ADGyksIZgnCE5ZkwJAY4sMpICZSZLh6RASmqSw-kOngRV1NQLhoLQfKUIlOETDFUUAI4xZAnXKTFyWlIlqlsJ1PXKYO4BzhCA4TmSc0lcormTjmfB2cxt4uMxY7bStC2lUtm0sEAA)

Can you explain why you chose 10k for R5?

**Comment by jpraus** [comment]
Hi! Thank you for your feedback.
I believe your simulation is wrong. The R5 is a pull-down resistor for the input pin of the MCU. The R5 in simulation works as a voltage divider, which is not true when connected to MCU GPIO.

**Comment by jpraus** [comment]
What does it mean that the gateway locks itself?

**Comment by NijzinkM** [comment]
Thank you for the explanation. Out of curiosity I lowered R5 to 1.5k, which is low for a pull-down resistor but not problematic. It may have something to do with the optocouplers I'm using. I will let you know how it works out.

By locking I mean that the MCU doensn't boot properly. It is powered but it doesn't send any data or response. GPIO's 0, 1, 2 and 15 affect the boot process of the ESP8266, but I'm not using those pins. I use 4, 5, 12 and 14. This might be a Wemos D1 issue.

You've answered my question about R5 so you can close the issue if you want.
