### ISSUE TITLE
How much power does the board require?

### ISSUE THREAD

**Issue by JoepBakker** [jpraus/arduino-opentherm#39]
I recently bought the OpenTherm shield, but I am not sure what the amp rating of the 24V power supply should be. Does anyone have any information about the idle power consumption and max power consumption of the board (combined with an ESP32)?
Thanks in advance!

**Comment by jpraus** [comment]
Hi Joe! Depending on what you are going to power with it. Normalny for MCU and the thermostat the 0.5A is enough.
