### ISSUE TITLE
How to connect power during self test?

### ISSUE THREAD

**Issue by JoepBakker** [jpraus/arduino-opentherm#40]
Hi,

I was wondering how I should connect the power while running selftest. In the instructions, it says to connect the 24V power supply. Is it still safe to connect the 5V power supply (USB) to the arduino? 

In the section before, for the hardware test, the instructions specify that the 5V supply should be disconnected. If this is also the case for the self test, could anyone maybe help me with how to connect the serial monitor without providing power?

Thanks in advance!

**Comment by jpraus** [comment]
It's safe to connect the USB to Arduino, It has an auto-power select which will block the 5V coming from USB if there is external power.

**Comment by JoepBakker** [comment]
Awesome, thanks!
